/**
 * 
 */
package com.honda.cart2.dataaccess.eventprocessing;

/**
 * @author VCC89569
 *
 */
public interface EventProcessingSQLIF {
	
	public static final String EVENT_NAME_DD = "SELECT  EEM.PH_COST_EVENT_NAME, EEM.EVENT_REV_NO, EEM.PH_COST_EVENT_NAME CONCAT '  ' CONCAT CHAR(EEM.EVENT_REV_NO) AS EVENT, " +
	"PH_COST_EVENT_TEXT,  PH_CMS_ITEM_CODE FROM FCEEM1 EEM WHERE EVENT_VISIBLE_CODE = 0 AND EXISTS ( " +
	"SELECT * FROM FCEAD1 EAD WHERE EAD.PH_COST_EVENT_NAME = EEM.PH_COST_EVENT_NAME AND EAD.EVENT_REV_NO = EEM.EVENT_REV_NO " +
	"AND EAD.PH_EVENT_ACT_CODE = 'LD') AND (EEM.PH_COST_EVENT_NAME LIKE ? OR EEM.PH_COST_EVENT_NAME LIKE ? OR (EEM.PH_COST_EVENT_NAME LIKE ? AND  ( left (TRIM(PH_COST_EVENT_NAME) , 1) BETWEEN '0' and '9' )))" +
	"  ORDER BY EEM.PH_COST_EVENT_NAME";
	
	public static final String EVENT_NAME_DD_ALL_EVENTS = "SELECT  EEM.PH_COST_EVENT_NAME, EEM.EVENT_REV_NO, EEM.PH_COST_EVENT_NAME CONCAT '  ' CONCAT CHAR(EEM.EVENT_REV_NO) AS EVENT, " +
	"PH_COST_EVENT_TEXT,  PH_CMS_ITEM_CODE FROM FCEEM1 EEM WHERE EVENT_VISIBLE_CODE = 0 AND EXISTS ( " +
	"SELECT * FROM FCEAD1 EAD WHERE EAD.PH_COST_EVENT_NAME = EEM.PH_COST_EVENT_NAME AND EAD.EVENT_REV_NO = EEM.EVENT_REV_NO " +
	"AND EAD.PH_EVENT_ACT_CODE = 'LD') ";
	
	public static final String EVENT_NAME_DD_WHERE_CLAUSE_MPC_ROLES = " AND (TRIM(PH_COST_EVENT_NAME) like ? OR TRIM(PH_COST_EVENT_NAME) like ? OR (TRIM(PH_COST_EVENT_NAME) like ? AND TRIM(PH_COST_EVENT_NAME) not like ? ))";
	
	public static final String EVENT_NAME_DD_WHERE_CLAUSE_PSP_ROLES = " AND (TRIM(PH_COST_EVENT_NAME) like ? OR (TRIM(PH_COST_EVENT_NAME) like ? AND (TRIM(PH_COST_EVENT_NAME) like ? AND  left (TRIM(PH_COST_EVENT_NAME) , 1) NOT BETWEEN '0' and '9' ))) ";
	
	// CPT-846
	public static final String EVENT_NAME_DD_WHERE_CLAUSE_MEX_ROLES = " AND (TRIM(PH_COST_EVENT_NAME) like ? OR (TRIM(PH_COST_EVENT_NAME) like ? AND (TRIM(PH_COST_EVENT_NAME) like ? AND  left (TRIM(PH_COST_EVENT_NAME) , 1) NOT BETWEEN '0' and '9' ))) ";
		
	//public static final String EVENT_NAME_DD_WHERE_CLAUSE_OTHER_ROLES = " AND (TRIM(PH_COST_EVENT_NAME) like ? OR TRIM(PH_COST_EVENT_NAME) like ? OR TRIM(PH_COST_EVENT_NAME) like ? OR TRIM(PH_COST_EVENT_NAME) like ? )";
	public static final String EVENT_NAME_DD_WHERE_CLAUSE_OTHER_ROLES = " AND (TRIM(PH_COST_EVENT_NAME) like ? OR TRIM(PH_COST_EVENT_NAME) like ? OR TRIM(PH_COST_EVENT_NAME) like ? OR TRIM(PH_COST_EVENT_NAME) like ? OR TRIM(PH_COST_EVENT_NAME) like ? )";
	// CPT-846
	public static final String EVENT_NAME_DD_WHERE_CLAUSE_OTHER_ROLES_5 = " AND (TRIM(PH_COST_EVENT_NAME) like ? OR TRIM(PH_COST_EVENT_NAME) like ? OR TRIM(PH_COST_EVENT_NAME) like ? OR TRIM(PH_COST_EVENT_NAME) like ? OR TRIM(PH_COST_EVENT_NAME) like ? )";
	
	public static final String EVENT_NAME_DD_ORDER_BY_CLAUSE = "ORDER BY"+ 
    " CASE"+
        " WHEN EEM.PH_CMS_ITEM_CODE = 'MPCE' THEN 1"+
        " WHEN EEM.PH_CMS_ITEM_CODE = 'BUCE' THEN 2"+
        " ELSE 3"+
    " END,"+
    " EEM.DATA_MAINT_TSTP DESC;";
	
	public static final String HAM_PLANT_DD = "SELECT CODE, CODE_DESC_TEXT, STRIP(CODE) CONCAT ' - ' CONCAT CODE_DESC_TEXT AS DISPLAY_CODE " +
	"FROM --DBA_SCHEMA--.DACOD1 WHERE CODE_NAME = 'PLANT_LOC_CODE'";
	
	public static final String PAYMENT_CURR_DD = "SELECT CODE, CODE_DESC_TEXT, STRIP(CODE) CONCAT ' - ' CONCAT CODE_DESC_TEXT AS DISPLAY_CODE " +
	"FROM --DBA_SCHEMA--.DACOD1 WHERE CODE_NAME = 'ISO_CURRENCY_CODE' ORDER BY CODE DESC";
	
	public static final String PAYMENTR_CURR_DD = "SELECT CODE, CODE_DESC_TEXT, STRIP(CODE) CONCAT ' - ' CONCAT CODE_DESC_TEXT AS DISPLAY_CODE " +
	"FROM FCCOD1 WHERE CODE_NAME = 'ISO_CURRENCY_CODE'";
	
	public static final String COPY_PAYMENT_CURR_DD = "SELECT CODE ,CODE_DESC_TEXT ,STRIP(CODE) CONCAT ' - ' CONCAT CODE_DESC_TEXT AS DISPLAY_CODE " +
	" FROM FCCOD1 WHERE CODE_NAME = 'ISO_CURRENCY_CODE' ";
	
	public static final String PROC_GRP_DD = "SELECT CODE, CODE_DESC_TEXT, STRIP(CODE) CONCAT ' - ' CONCAT CODE_DESC_TEXT AS DISPLAY_CODE " +
	"FROM --DBA_SCHEMA--.DACOD1 WHERE CODE_NAME = 'PROC_SECT_CODE'";
	
	public static final String DESIGN_SECTION_DD = "SELECT CODE, CODE_DESC_TEXT, STRIP(CODE) CONCAT ' - ' CONCAT CODE_DESC_TEXT AS DISPLAY_CODE " +
	"FROM --DBA_SCHEMA--.DACOD1 WHERE CODE_NAME =  'PART_SECTION_CODE'";
	
	public static final String CARRY_EXCLUSIVE_DD = "SELECT CODE, CODE_DESC_TEXT, STRIP(CODE) CONCAT ' - ' CONCAT CODE_DESC_TEXT AS DISPLAY_CODE " +
	"FROM FCCOD1 WHERE CODE_NAME = 'INV_STAGE_CODE'";
	
	public static final String COST_CATEGORY_DD = "SELECT DISTINCT COD1.CODE, COD1.CODE_DESC_TEXT, " +
	"STRIP(COD1.CODE) CONCAT ' - ' CONCAT COD1.CODE_DESC_TEXT AS DISPLAY_CODE FROM FCCOD1 COD1 INNER JOIN FCCOD1 COD2 ON COD1.CODE = COD2.CODE";
		   
    public static final String COST_CATEGORY_PART_COST_DD = " SELECT DISTINCT COD1.CODE, " +
   		" COD1.CODE_DESC_TEXT, " +
   		" STRIP(COD1.CODE) CONCAT ' - ' CONCAT COD1.CODE_DESC_TEXT AS DISPLAY_CODE " +
   		" FROM FCCOD1 COD1 INNER JOIN FCCOD1 COD2 ON COD1.CODE = COD2.CODE WHERE COD1.CODE_NAME = 'COST_CHG_CAT_CODE' " +
   		" AND COD2.CODE_NAME =  COD2.CODE_NAME ";
	
	public static final String PLANT_CODE_DD = "SELECT CODE, CODE_DESC_TEXT FROM FCCOD1 WHERE CODE_NAME = 'TGT_PLANT_LOC_CODE'";
	
	public static final String FREEZE_CODE_CHECK = "SELECT EAU.UPD_ACTIVITY_CODE FROM FCEAU1 EAU WHERE EAU.PH_COST_EVENT_NAME = ? AND EAU.EVENT_REV_NO = ?";
	
	public static final String COST_CHANGES_GRID = " SELECT GCG.PRI_COST_CHG_CODE, GCG.COST_CHANGE_CODE, COD.CODE_DESC_TEXT, EPC.COST_CHANGE_AMT, " +
	   "EPC.ACT_QUOTE_EFF_DATE, EPC.ACT_QUOTE_EFF_DATE AS NEW_QUOTE_EFF_DATE, EPC.COMMENT_TEXT FROM FCGCG1 GCG LEFT OUTER JOIN " +
	   "(SELECT COST_CHANGE_CODE, PH_COST_EVENT_NAME, EVENT_REV_NO, COST_CHANGE_AMT, ACT_QUOTE_EFF_DATE, COMMENT_TEXT FROM FCEPC1 " + 
	  "WHERE PH_COST_EVENT_NAME = ? AND EVENT_REV_NO = ? AND PART_NO =  ? " +
	  "AND PART_COLOR_CODE =   ? AND PLANT_LOC_CODE =  ? AND SUPPLIER_NO = ? " +
	  "AND COST_CHG_CAT_CODE = 'MCC' ) EPC ON GCG.COST_CHANGE_CODE = EPC.COST_CHANGE_CODE " +
	  "INNER JOIN FCCOD1 COD ON GCG.COST_CHANGE_CODE = COD.CODE	WHERE GCG.COST_FUNC_GRP_CODE = 'PPQU' AND COD.CODE_NAME = 'COST_CHANGE_CODE' " +
	  "ORDER BY GCG.PRI_COST_CHG_CODE, GCG.COST_CHANGE_CODE";
	
	public static final String PROCESS_COST_CHANGES_GRID = " SELECT GCG.COST_CHANGE_CODE, COD.CODE_DESC_TEXT, EPC.COST_CHANGE_AMT, " +
	   "EPC.ACT_QUOTE_EFF_DATE, EPC.ACT_QUOTE_EFF_DATE AS NEW_QUOTE_EFF_DATE, TRIM(EPC.COMMENT_TEXT) AS COMMENT_TEXT, EPC.COST_CHANGE_AMT_JPY, EPC.ISO_CURRENCY_CODE FROM FCGCG1 GCG INNER JOIN " +
	   "(SELECT COST_CHANGE_CODE, PH_COST_EVENT_NAME, EVENT_REV_NO, COST_CHANGE_AMT, ACT_QUOTE_EFF_DATE, " +
	   " TRIM(COMMENT_TEXT) AS COMMENT_TEXT, COST_CHANGE_AMT_JPY, ISO_CURRENCY_CODE "+
	   " FROM FCEPC1 WHERE PH_COST_EVENT_NAME = ? AND EVENT_REV_NO = ? AND PART_NO =  ? " +
	  "AND PART_COLOR_CODE =   ? AND PLANT_LOC_CODE =  ? AND SUPPLIER_NO = ? " +
	  "AND COST_CHG_CAT_CODE = 'MCC')"+
	  " EPC ON GCG.COST_CHANGE_CODE = EPC.COST_CHANGE_CODE " +
	  "INNER JOIN FCCOD1 COD ON GCG.COST_CHANGE_CODE = COD.CODE	WHERE GCG.COST_FUNC_GRP_CODE = 'PPQU' AND COD.CODE_NAME = 'COST_CHANGE_CODE' " +
	  "ORDER BY GCG.PRI_COST_CHG_CODE, GCG.COST_CHANGE_CODE";
	
	public static final String PURCHASE_COST_CHANGES_GRID = " SELECT GCG.COST_CHANGE_CODE, COD.CODE_DESC_TEXT, EPC.COST_CHANGE_AMT, " +
	   "EPC.ACT_QUOTE_EFF_DATE, EPC.ACT_QUOTE_EFF_DATE AS NEW_QUOTE_EFF_DATE, TRIM(EPC.COMMENT_TEXT) AS COMMENT_TEXT, EPC.COST_CHANGE_AMT_JPY, EPC.ISO_CURRENCY_CODE FROM FCGCG1 GCG INNER JOIN " +
	   "(SELECT COST_CHANGE_CODE, PH_COST_EVENT_NAME, EVENT_REV_NO, COST_CHANGE_AMT, ACT_QUOTE_EFF_DATE, " +
	   " TRIM(COMMENT_TEXT) AS COMMENT_TEXT, COST_CHANGE_AMT_JPY, ISO_CURRENCY_CODE "+
	   " FROM FCEPC1 WHERE PH_COST_EVENT_NAME = ? AND EVENT_REV_NO = ? AND PART_NO =  ? " +
	  "AND PART_COLOR_CODE =   ? AND PLANT_LOC_CODE =  ? AND SUPPLIER_NO = ? " +
	  "AND COST_CHG_CAT_CODE = 'PCC')"+
	  " EPC ON GCG.COST_CHANGE_CODE = EPC.COST_CHANGE_CODE " +
	  "INNER JOIN FCCOD1 COD ON GCG.COST_CHANGE_CODE = COD.CODE	WHERE GCG.COST_FUNC_GRP_CODE = 'PPQU' AND COD.CODE_NAME = 'COST_CHANGE_CODE' " +
	  "ORDER BY GCG.PRI_COST_CHG_CODE, GCG.COST_CHANGE_CODE";
	
	public static final String COST_CHANGES_GRID_E2CE = "SELECT GCG.COST_CHANGE_CODE, COD.CODE_DESC_TEXT, EPC.COST_CHANGE_AMT, EPC.COST_CHANGE_AMT_JPY, " +
			" EPC.ACT_QUOTE_EFF_DATE, EPC.ACT_QUOTE_EFF_DATE AS NEW_QUOTE_EFF_DATE, EPC.COMMENT_TEXT FROM FCGCG1 GCG INNER JOIN " +
			" (SELECT SUM(COST_CHANGE_AMT) AS COST_CHANGE_AMT, SUM(COST_CHANGE_AMT_JPY) AS COST_CHANGE_AMT_JPY, COST_CHANGE_CODE, MAX(COMMENT_TEXT) AS COMMENT_TEXT, " +
			" SUBSTR(CHAR(TO_DATE(YEAR(ACT_QUOTE_EFF_DATE) CONCAT '-' CONCAT MONTH(ACT_QUOTE_EFF_DATE) CONCAT '-' CONCAT varchar(1), 'YYYY-MM-DD')), 1, 10) AS ACT_QUOTE_EFF_DATE " +
			" FROM FCEPC1 WHERE PH_COST_EVENT_NAME = ? AND EVENT_REV_NO = ? AND PART_NO = ? AND PART_COLOR_CODE = ? AND PLANT_LOC_CODE = ? " +
			" AND SUPPLIER_NO = ? AND COST_CHG_CAT_CODE = 'MCC' GROUP BY  COST_CHANGE_CODE, YEAR(ACT_QUOTE_EFF_DATE), MONTH(ACT_QUOTE_EFF_DATE))" +
			" EPC ON GCG.COST_CHANGE_CODE = EPC.COST_CHANGE_CODE INNER JOIN FCCOD1 COD ON GCG.COST_CHANGE_CODE = COD.CODE " +
			" WHERE GCG.COST_FUNC_GRP_CODE = 'PPQU' AND COD.CODE_NAME = 'COST_CHANGE_CODE' ORDER BY GCG.PRI_COST_CHG_CODE, GCG.COST_CHANGE_CODE";
	
	public static final String EVENT_NAME_PRD_VOL_DD = " SELECT  EEM.PH_COST_EVENT_NAME, EEM.EVENT_REV_NO, EEM.PH_COST_EVENT_NAME CONCAT '  ' CONCAT CHAR(EEM.EVENT_REV_NO) AS EVENT, " +
    "EEM.PH_COST_EVENT_TEXT, EEM.BUD_MO_PER_QTY FROM FCEEM1 EEM WHERE EVENT_VISIBLE_CODE = 0 AND PH_CMS_ITEM_CODE = 'BUCE' AND " +
    "EXISTS (SELECT * FROM FCEAD1 EAD WHERE EAD.PH_COST_EVENT_NAME = EEM.PH_COST_EVENT_NAME AND EAD.EVENT_REV_NO = EEM.EVENT_REV_NO " +
    "AND EAD.PH_EVENT_ACT_CODE = 'LD') ORDER BY EEM.PH_COST_EVENT_NAME";

	// CPT-846 Assume that MEX cannot see PSP or Other
	public static final String EVENT_NAME_PRD_VOL_DD_MEX = " SELECT  EEM.PH_COST_EVENT_NAME, EEM.EVENT_REV_NO, EEM.PH_COST_EVENT_NAME CONCAT '  ' CONCAT CHAR(EEM.EVENT_REV_NO) AS EVENT, " +
		    "EEM.PH_COST_EVENT_TEXT, EEM.BUD_MO_PER_QTY FROM FCEEM1 EEM WHERE EVENT_VISIBLE_CODE = 0 AND PH_CMS_ITEM_CODE = 'BUCE' AND " +
		    "EXISTS (SELECT * FROM FCEAD1 EAD WHERE EAD.PH_COST_EVENT_NAME = EEM.PH_COST_EVENT_NAME AND EAD.EVENT_REV_NO = EEM.EVENT_REV_NO " +
		    "AND EAD.PH_EVENT_ACT_CODE = 'LD') AND PH_COST_EVENT_NAME LIKE '%MEX%' ORDER BY EEM.PH_COST_EVENT_NAME";

	// CPT-846 Assume that PSP cannot see others like MEX
	public static final String EVENT_NAME_PRD_VOL_DD_PSP = " SELECT  EEM.PH_COST_EVENT_NAME, EEM.EVENT_REV_NO, EEM.PH_COST_EVENT_NAME CONCAT '  ' CONCAT CHAR(EEM.EVENT_REV_NO) AS EVENT, " +
		    "EEM.PH_COST_EVENT_TEXT, EEM.BUD_MO_PER_QTY FROM FCEEM1 EEM WHERE EVENT_VISIBLE_CODE = 0 AND PH_CMS_ITEM_CODE = 'BUCE' AND " +
		    "EXISTS (SELECT * FROM FCEAD1 EAD WHERE EAD.PH_COST_EVENT_NAME = EEM.PH_COST_EVENT_NAME AND EAD.EVENT_REV_NO = EEM.EVENT_REV_NO " +
		    "AND EAD.PH_EVENT_ACT_CODE = 'LD') AND PH_COST_EVENT_NAME LIKE '%PSP%' ORDER BY EEM.PH_COST_EVENT_NAME";
	
	
	public static final String PLANT_LOCATION_PRD_VOL_DD = "SELECT DISTINCT ERA.TGT_PLANT_LOC_CODE, COD.CODE_DESC_TEXT, " +
			"STRIP(ERA.TGT_PLANT_LOC_CODE) CONCAT ' - ' CONCAT COD.CODE_DESC_TEXT AS DISPLAY_CODE FROM FCERA1 ERA " +
			"INNER JOIN (SELECT * FROM --DBA_SCHEMA--.DACOD1 WHERE CODE_NAME = 'TGT_PLANT_LOC_CODE') COD ON ERA.TGT_PLANT_LOC_CODE = COD.CODE " +
			"WHERE ERA.PH_COST_EVENT_NAME = ? AND ERA.EVENT_REV_NO = ? ORDER BY TGT_PLANT_LOC_CODE";
	
	//Get Model values when only Event Name is selected from Dropdown. Here Plant Loc is not selected,so not present in WHERE clause.
	public static final String MODEL_PRD_VOL_DD_1 = "SELECT DISTINCT ERA.TGT_MODEL_DEV_CODE FROM FCERA1 ERA " +
	"WHERE ERA.PH_COST_EVENT_NAME = ? AND ERA.EVENT_REV_NO = ? ORDER BY TGT_MODEL_DEV_CODE"; //AND ERA.TGT_PLANT_LOC_CODE = ?
	
	public static final String MODEL_PRD_VOL_DD = "SELECT DISTINCT ERA.TGT_MODEL_DEV_CODE FROM FCERA1 ERA " +
			"WHERE ERA.PH_COST_EVENT_NAME = ? AND ERA.EVENT_REV_NO = ? " +
			"AND ERA.TGT_PLANT_LOC_CODE = ? ORDER BY TGT_MODEL_DEV_CODE";
	
	public static final String TYPE_PRD_VOL_DD_2 = "SELECT DISTINCT ERA.MTC_TYPE FROM FCERA1 ERA " +
	"WHERE ERA.PH_COST_EVENT_NAME = ? AND ERA.EVENT_REV_NO = ? " +
	"AND ERA.TGT_PLANT_LOC_CODE = ? ORDER BY MTC_TYPE";
	
	public static final String TYPE_PRD_VOL_DD_1 = "SELECT DISTINCT ERA.MTC_TYPE FROM FCERA1 ERA " +
	"WHERE ERA.PH_COST_EVENT_NAME = ? AND ERA.EVENT_REV_NO = ? ORDER BY MTC_TYPE";
	
	public static final String TYPE_PRD_VOL_DD = "SELECT DISTINCT ERA.MTC_TYPE FROM FCERA1 ERA " +
			"WHERE ERA.PH_COST_EVENT_NAME = ? AND ERA.EVENT_REV_NO = ? " +
			"AND ERA.TGT_PLANT_LOC_CODE = ? AND ERA.TGT_MODEL_DEV_CODE = ? " +
			"ORDER BY MTC_TYPE";
	
	public static final String OPTION_PRD_VOL_DD_2 = "SELECT DISTINCT ERA.MTC_OPTION FROM FCERA1 ERA WHERE ERA.PH_COST_EVENT_NAME = ? " +
	"AND ERA.EVENT_REV_NO = ? AND ERA.TGT_PLANT_LOC_CODE = ? AND NOT ERA.MTC_OPTION = '' ORDER BY MTC_OPTION"; //ERA.TGT_MODEL_DEV_CODE = ? AND ERA.MTC_TYPE = ?  
	
	public static final String OPTION_PRD_VOL_DD_1 = "SELECT DISTINCT ERA.MTC_OPTION FROM FCERA1 ERA WHERE ERA.PH_COST_EVENT_NAME = ? " +
	"AND ERA.EVENT_REV_NO = ?  AND NOT ERA.MTC_OPTION = '' ORDER BY MTC_OPTION";
	
	public static final String OPTION_PRD_VOL_DD = "SELECT DISTINCT ERA.MTC_OPTION FROM FCERA1 ERA WHERE ERA.PH_COST_EVENT_NAME = ? " +
			"AND ERA.EVENT_REV_NO = ? AND ERA.TGT_PLANT_LOC_CODE = ? AND ERA.TGT_MODEL_DEV_CODE = ? AND ERA.MTC_TYPE = ? " +
			"AND NOT ERA.MTC_OPTION = '' ORDER BY MTC_OPTION";
	
	//in use query dynamic building
	public static final String POPULATE_PLANT_LOCATION_PRD_VOL_DD = "SELECT DISTINCT ERA.TGT_PLANT_LOC_CODE, COD.CODE_DESC_TEXT, " +
	"STRIP(ERA.TGT_PLANT_LOC_CODE) CONCAT ' - ' CONCAT COD.CODE_DESC_TEXT AS DISPLAY_CODE FROM FCERA1 ERA " +
	"INNER JOIN (SELECT * FROM --DBA_SCHEMA--.DACOD1 WHERE CODE_NAME = 'TGT_PLANT_LOC_CODE') COD ON ERA.TGT_PLANT_LOC_CODE = COD.CODE " +
	"--WHERE_CONDITION-- " +
	" ORDER BY TGT_PLANT_LOC_CODE";
	
	public static final String POPULATE_MTC_MODEL_PRD_VOL_DD = "SELECT DISTINCT ERA.TGT_MODEL_DEV_CODE " +
	" FROM FCERA1 ERA " +
	"--WHERE_CONDITION-- " +
	" ORDER BY TGT_MODEL_DEV_CODE";
	
	public static final String POPULATE_MTC_TYPE_PRD_VOL_DD = "SELECT DISTINCT ERA.MTC_TYPE " +
	" FROM FCERA1 ERA " +
	" --WHERE_CONDITION-- " +
	" ORDER BY MTC_TYPE";
	
	public static final String POPULATE_MTC_OPTION_PRD_VOL_DD = "SELECT DISTINCT ERA.MTC_OPTION " +
	" FROM FCERA1 ERA " +
	" --WHERE_CONDITION-- "+
	" ORDER BY MTC_OPTION";
	
	/**
	 * For CODE_NAME='ESSBASE_MAP_WEIGHT' data needs to be fetched from EBM1 table and not from COD1 table
	 * length of column 'CODE' required is higher for CODE_NAME='ESSBASE_MAP_WEIGHT', thats why new table EBM1 table is created.
	 */
	
	public static final String CODE_NAME_DD = "SELECT DISTINCT CODE_NAME FROM FCCOD1";
	
	public static final String CODE_NAME_DD_EBM1 = " UNION SELECT DISTINCT CODE_NAME FROM FCEBM1 ORDER BY 1";
	
	public static final String CODES_SELECT_GRID = "SELECT CODE_NAME, CODE, ABBR_CDE_DESC_TEXT, CODE_DESC_TEXT FROM FCCOD1 " +
			"WHERE CODE_NAME= CODE_NAME AND CODE= CODE";
	
	public static final String UPDATE_CODES_GRID = "UPDATE --TABLE_NAME-- SET CODE = ?, ABBR_CDE_DESC_TEXT = ?, " +
			"CODE_DESC_TEXT    = ?, MAINT_LOGON_ID_NO = ?, DATA_MAINT_PROG_NO = ?, " +
			"DATA_MAINT_TSTP = CURRENT TIMESTAMP WHERE CODE_NAME = ? AND CODE = ? ";
	
	public static final String DELETE_CODES = "DELETE FROM --TABLE_NAME-- WHERE CODE_NAME = ? AND CODE = ?";
	
	public static final String INSERT_FOCUS_CODE = "INSERT INTO --TABLE_NAME-- (CODE_NAME, CODE, ABBR_CDE_DESC_TEXT, CODE_DESC_TEXT, MAINT_LOGON_ID_NO, " +
			"DATA_MAINT_PROG_NO, DATA_MAINT_TSTP ) VALUES ( ?, ?, ?, ?, ?, " +
			"'FCCOD1A', CURRENT TIMESTAMP )";
			
	public static final String UPDATE_EVENT_PART_LIST = "UPDATE FCEPM1 SET PROC_SECT_CODE = :procSectCode ,PART_STAGE_CODE = :partStageCode ,MAINT_LOGON_ID_NO = :maintLogonId " +
			" , DATA_MAINT_PROG_NO = :dataMaintProgNo , DATA_MAINT_TSTP   = CURRENT TIMESTAMP " +
			" WHERE PH_COST_EVENT_NAME = :eventName AND  EVENT_REV_NO = :eventRevNo AND  PART_NO = :partNo AND  PART_COLOR_CODE = :partColorCode AND  SUPPLIER_NO = :supplierNo" +
			" AND EXISTS (SELECT * FROM --DBA_SCHEMA--.DACOD1 WHERE CODE_NAME = 'PROC_SECT_CODE' AND CODE = :procSectCode) " +
			" AND EXISTS (SELECT * FROM FCCOD1 WHERE CODE_NAME = 'PART_STAGE_CODE' AND CODE = :partStageCode) ";
	
	public static final String UPDATE_EVENT_PART_LIST2 = "UPDATE FCEPM1 SET PROC_SECT_CODE = ? ,PART_STAGE_CODE = ? ,MAINT_LOGON_ID_NO = ? " +
	" , DATA_MAINT_PROG_NO = ? , DATA_MAINT_TSTP   = CURRENT TIMESTAMP " +
	" WHERE PH_COST_EVENT_NAME = ? AND  EVENT_REV_NO = ? AND  PART_NO = ? AND  PART_COLOR_CODE = ? AND  SUPPLIER_NO = ?" +
	" AND EXISTS (SELECT * FROM --DBA_SCHEMA--.DACOD1 WHERE CODE_NAME = 'PROC_SECT_CODE' AND CODE = ?) " +
	" AND EXISTS (SELECT * FROM FCCOD1 WHERE CODE_NAME = 'PART_STAGE_CODE' AND CODE = ?) ";

	//Change for PSCC-5467 start

	//public static final String PART_COLOR_DETAILS = "SELECT DISTINCT PART_COLOR_CODE FROM FCERA1";
		public static final String PART_COLOR_DETAILS =

		    "SELECT DISTINCT PART_COLOR_CODE " +
		    "FROM ( " +
		    "    SELECT PART_COLOR_CODE FROM TIX.TIKAF1 WHERE PART_NO = ? " +
		    "    UNION ALL " +
		    "    SELECT PART_COLOR_CODE FROM TIX.TIOAF1 WHERE PART_NO = ? " +
		    ") COLORS";
	//Change for PSCC-5467 end
	
	public static final String GET_PART_DETAILS = "SELECT M.PH_COST_EVENT_NAME ,M.EVENT_REV_NO ,M.PART_NO ,M.PART_COLOR_CODE ,M.SUPPLIER_NO ,M.PROC_SECT_CODE" +
			" ,M.PART_STAGE_CODE ,M.RPT_CURRENCY_CODE ,M.ISO_CURRENCY_CODE ,M.DC_NO ,M.EST_CYCLE_UNIT_QTY ,M.INVEST_COST_CODE ,M.PART_ADD_CODE " +
			" FROM FCEPM1 M WHERE M.PH_COST_EVENT_NAME = ? AND M.EVENT_REV_NO = ? AND M.PART_NO = ? AND M.PART_COLOR_CODE = ? AND M.SUPPLIER_NO = ?";
	
	public static final String GET_PART_APPLICATION_LIST = "{CALL --PROC_SCHEMA--.FCS622P(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?  ,?,?,?,? )}";
	
	public static final String GROUP_CODES = "SELECT DISTINCT COST_FUNC_GRP_CODE FROM FCGCG1";
	
	public static final String GROUP_CODES_FIND = "SELECT COST_FUNC_GRP_CODE, PRI_COST_CHG_CODE, COST_CHANGE_CODE FROM FCGCG1 " +
			"WHERE COST_FUNC_GRP_CODE =  COST_FUNC_GRP_CODE AND PRI_COST_CHG_CODE =  PRI_COST_CHG_CODE AND COST_CHANGE_CODE =  COST_CHANGE_CODE " +
			"ORDER BY PRI_COST_CHG_CODE, COST_CHANGE_CODE";
	
	public static final String GRP_CODES_DEL = "DELETE FROM FCGCG1 WHERE COST_FUNC_GRP_CODE = ? " +
			"AND PRI_COST_CHG_CODE = ? AND COST_CHANGE_CODE = ?";
	
	public static String ADD_GEN_CST_GRP = "INSERT INTO FCGCG1 (COST_FUNC_GRP_CODE, PRI_COST_CHG_CODE, COST_CHANGE_CODE, MAINT_LOGON_ID_NO, DATA_MAINT_PROG_NO, DATA_MAINT_TSTP) " +
	"VALUES (?, ?, ?, ?, 'FCGCGD1A', CURRENT TIMESTAMP)";
	
	public static final String GET_NM_PART_COST_LIST = "CALL --PROC_SCHEMA--.FCS621P (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	
	public static String GET_BU_PART_COST_LIST = "CALL --PROC_SCHEMA--.FCS506P (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	
	public static final String GET_MP_PART_COST_LIST ="CALL --PROC_SCHEMA--.FCS615P (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?,?)";
   	
	public static final String GET_PH_CMS_ITEM_CODE = "SELECT EEM.PH_CMS_ITEM_CODE FROM FCEEM1 EEM WHERE EEM.PH_COST_EVENT_NAME = ? AND EEM.EVENT_REV_NO = ? ";
	//change pscc-6605
	public static final String UPDATE_EVENT_APPLICATION_DETAILS =
		    "UPDATE FCEPA1 " +
		    "SET SHARE_RATE_PERCENT = ?, " +
		    "    PART_QTY = ?, " +
		    "    PART_SECTION_CODE = ? " +
		    "WHERE PH_COST_EVENT_NAME = ? " +
		    "AND EVENT_REV_NO = ? " +
		    "AND PART_NO = ? " +
		    "AND PART_COLOR_CODE = ? " +
		    "AND SUPPLIER_NO = ? " +
		    "AND SHIP_TO_CODE = ? " +
		    "AND PART_SECTION_CODE = ? " +   // OLD Section Code
		    "AND TGT_PLANT_LOC_CODE = ? " +
		    "AND TGT_MODEL_DEV_CODE = ? " +
		    "AND MTC_TYPE = ? " +
		    "AND MTC_OPTION = ? " +
		    "AND MODEL_CAT_CODE = ?";

        //change pscc-6605
	
	public static final String ADD_NEW_EVENT_PART = "CALL --PROC_SCHEMA--.FCS601P (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	
	public static final String UPDATE_EVENT_PART_DETAILS = "CALL --PROC_SCHEMA--.FCS603P (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	
	public static final String DELETE_EVENT_PART = "CALL --PROC_SCHEMA--.FCS602P (?, ?, ?, ?, ?, ?, ?, ?)";
	
	public static final String UPDATE_EVENT_PART_COST_LIST = "UPDATE FCEPC1 SET COST_CHANGE_AMT = ?, MAINT_LOGON_ID_NO = ?, " +
			" DATA_MAINT_PROG_NO = ? , DATA_MAINT_TSTP = CURRENT TIMESTAMP WHERE PH_COST_EVENT_NAME = ? AND EVENT_REV_NO = ? " +
			" AND PART_NO = ? AND PART_COLOR_CODE = ? AND SUPPLIER_NO = ? AND PLANT_LOC_CODE = ?  AND COST_CHG_CAT_CODE = 'BC'";
	
	public static final String UPDATE_REVIEW_COST_CHANGE_BUCE = "UPDATE FCEPC1" +
			"   SET COST_CHANGE_AMT = ?," +
			"   ISO_CURRENCY_CODE  = ?," +
			"  DATA_MAINT_PROG_NO = ?," +
			"   MAINT_LOGON_ID_NO = ?," +
			"   DATA_MAINT_TSTP = CURRENT TIMESTAMP " +
			"   WHERE PH_COST_EVENT_NAME = ?" +
			"  AND EVENT_REV_NO = ?" +
			"   AND PART_NO = ? " +
			"  AND PART_COLOR_CODE = ?" +
			"   AND SUPPLIER_NO = ?" +
			"   AND PLANT_LOC_CODE = ?" +
			"   AND COST_CHG_CAT_CODE = 'BC'";
			
    public static final String GET_PART = "SELECT BASIC_PART_NAME FROM --TIX_SCHEMA--.TIBNM1 WHERE TGT_BASIC_PART_NO = ? AND TGT_LANGUAGE_CODE = '2'";
    
    public static final String GET_EVENT_NEW_PART = "SELECT PART_NAME FROM FCEPN1 WHERE PART_NO = ?";
    
    public static final String GET_SUPPLIER = "SELECT SUPPLIER_NAME FROM --PUR_SCHEMA--.PUOSM1 WHERE SUPPLIER_NO = ?";
    
    public static final String GET_FIELD_LEVEL_SECURITY = "CALL --PROC_SCHEMA--.FCS947P (?, ?, ?, ?, ?, ?, ?, ?, ?)";
    
    public static final String GET_APP_COPY_LIST = "SELECT EPA.PH_COST_EVENT_NAME ,EPA.EVENT_REV_NO,EPA.PART_NO ,EPA.PART_COLOR_CODE ,EPA.SUPPLIER_NO ,EPA.SHIP_TO_CODE " +
    		" ,EPA.PART_SECTION_CODE ,EPA.TGT_PLANT_LOC_CODE ,EPA.TGT_MODEL_DEV_CODE ,EPA.MTC_TYPE ,EPA.MTC_OPTION ,EPA.MODEL_CAT_CODE ,EPA.SHARE_RATE_PERCENT " +
    		" ,EPA.PART_QTY ,EPA.MAINT_LOGON_ID_NO ,EPA.DATA_MAINT_PROG_NO ,EPA.DATA_MAINT_TSTP, EPA.IS_DSPS FROM FCEPA1 AS EPA";
    
    public static final String GET_FROM_APP_COPY_LIST_WHERE_CLAUSE = " WHERE EPA.PH_COST_EVENT_NAME = ? AND EPA.EVENT_REV_NO = ? AND EPA.PART_NO = ? " +
    		" AND EPA.PART_COLOR_CODE = ? AND EPA.SUPPLIER_NO = ? "; 
    
    public static final String GET_TO_APP_COPY_LIST_WHERE_CLAUSE = " WHERE PH_COST_EVENT_NAME = '' ";
    
    public static final String GET_COST_COPY_LIST = "SELECT PH_COST_EVENT_NAME ,EVENT_REV_NO ,PART_NO ,PART_COLOR_CODE ,SUPPLIER_NO ,PLANT_LOC_CODE ,COST_BEG_EFF_DATE " +
    		" ,COST_CHG_CAT_CODE ,COST_CHANGE_CODE ,COST_CHANGE_AMT ,ACT_QUOTE_EFF_DATE FROM FCEPC1 ";
    
    public static final String GET_FROM_COST_COPY_LIST_WHERE_CLAUSE = " WHERE PH_COST_EVENT_NAME = ? AND EVENT_REV_NO = ? AND PART_NO = ? AND PART_COLOR_CODE = ? " +
    		" AND SUPPLIER_NO = ? AND COST_CHG_CAT_CODE = 'BC' ";
    
    public static final String GET_TO_COST_COPY_LIST_WHERE_CLAUSE = " WHERE PH_COST_EVENT_NAME = '' ";
    
    public static final String INSERT_PART_APP_FOR_COPY = "INSERT INTO FCEPA1 (PH_COST_EVENT_NAME ,EVENT_REV_NO,PART_NO ,PART_COLOR_CODE ,SUPPLIER_NO ,SHIP_TO_CODE " +
    		" ,PART_BLOCK_CODE ,PART_SECTION_CODE ,TGT_PLANT_LOC_CODE ,TGT_MODEL_DEV_CODE ,MTC_TYPE ,MTC_OPTION ,MODEL_CAT_CODE ,SHARE_RATE_PERCENT ,PART_QTY) " +
    		" VALUES ('|NEW_PH_COST_EVENT_NAME|'  ,|NEW_EVENT_REV_NO| ,'|NEW_PART_NO|' ,'|NEW_PART_COLOR_CODE|' ,'|NEW_SUPPLIER_NO|' ,'|SHIP_TO_CODE|' ,'|PART_BLOCK_CODE|' " +
    		" ,'|PART_SECTION_CODE|' ,'|TGT_PLANT_LOC_CODE|' ,'|TGT_MODEL_DEV_CODE|' ,'|MTC_TYPE|' ,'|MTC_OPTION|' ,'|MODEL_CAT_CODE|' ,|SHARE_RATE_PERCENT| ,|PART_QTY|)" ;
    
    public static final String GET_EVENT_PART_SUPPLIER_EXIST = "SELECT 1 FROM FCEPM1 WHERE PH_COST_EVENT_NAME = ? AND EVENT_REV_NO = ? AND PART_NO = ? AND PART_COLOR_CODE = ? AND SUPPLIER_NO = ?";
    
    public static final String COPY_EVENT_APPLICATION = "CALL --PROC_SCHEMA--.FCS618P(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?)";
    
    public static final String COPY_PART_COST = "INSERT INTO FCEPC1 " +
    		" (PH_COST_EVENT_NAME ,EVENT_REV_NO ,PART_NO ,PART_COLOR_CODE ,SUPPLIER_NO ,PLANT_LOC_CODE ,COST_BEG_EFF_DATE ,COST_CHG_CAT_CODE " +
    		" ,COST_CHANGE_CODE ,COST_CHANGE_AMT ,ACT_QUOTE_EFF_DATE ,MAINT_LOGON_ID_NO ,DATA_MAINT_PROG_NO ,DATA_MAINT_TSTP) " +
    		" VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT TIMESTAMP)";
    
    public static final String LOOKUP_EVENT_PARTS = "SELECT EVENT.PART_NO, PART.BASIC_PART_NAME AS PART_NAME " +
    		" FROM |!BASE_TABLE| AS EVENT, --TIX_SCHEMA--.TIBNM1 AS PART " +
    		" WHERE EVENT.PART_NO = PART.TGT_BASIC_PART_NO AND EVENT.PH_COST_EVENT_NAME = ? AND EVENT.EVENT_REV_NO = ? AND EVENT.PART_NO LIKE ? " +
    		" AND PART.TGT_LANGUAGE_CODE = '2' AND PART.BASIC_PART_NAME LIKE ? " +
    		" UNION " +
    		" SELECT EVENT.PART_NO, PART.PART_NAME " +
    		" FROM |!BASE_TABLE| AS EVENT, FCEPN1 AS PART " +
    		" WHERE EVENT.PART_NO = PART.PART_NO AND EVENT.PH_COST_EVENT_NAME = ? AND EVENT.EVENT_REV_NO = ? AND EVENT.PART_NO LIKE ? AND PART.PART_NAME LIKE ? " +
    		" FETCH FIRST 100 ROWS ONLY ";
    
    public static final String LOOKUP_PARTS = "SELECT TGT_BASIC_PART_NO AS PART_NO, BASIC_PART_NAME AS PART_NAME " +
    		" FROM --TIX_SCHEMA--.TIBNM1 WHERE TGT_LANGUAGE_CODE = '2' AND TGT_BASIC_PART_NO LIKE ? AND BASIC_PART_NAME LIKE ? " +
    		" UNION " +
    		" SELECT PART_NO, PART_NAME FROM FCEPN1 WHERE PART_NO LIKE ? AND PART_NAME LIKE ? " +
    		" FETCH FIRST 100 ROWS ONLY";
    
    public static final String LOOKUP_EVENT_SUPPLIER = "SELECT DISTINCT EVENT.SUPPLIER_NO, SUPP.SUPPLIER_NAME " +
    		" FROM |!BASE_TABLE| AS EVENT LEFT OUTER JOIN --PUR_SCHEMA--.PUOSM1 AS SUPP ON EVENT.SUPPLIER_NO = SUPP.SUPPLIER_NO " +
    		" WHERE EVENT.PH_COST_EVENT_NAME = ? AND EVENT.EVENT_REV_NO = ? AND EVENT.SUPPLIER_NO LIKE ? " +
    		" AND SUPP.SUPPLIER_NAME LIKE ? AND SUPP.SUPPLIER_LOC_CODE BETWEEN 0 AND 1 " +
    		" FETCH FIRST 100 ROWS ONLY";
    
    public static final String LOOKUP_SUPPLIER = "SELECT DISTINCT SUPPLIER_NO, SUPPLIER_NAME FROM --PUR_SCHEMA--.PUOSM1 " +
    		" WHERE SUPPLIER_NO LIKE ? AND SUPPLIER_NAME LIKE ? AND SUPPLIER_LOC_CODE BETWEEN 0 AND 1 " +
    		" FETCH FIRST 100 ROWS ONLY";
    
    public static final String GET_UNIT_LEVEL_SUPPLIER = "SELECT CODE_DESC_TEXT FROM FCCOD1 WHERE CODE_NAME = 'UNIT_LEVEL_SUPP' AND CODE = ?";
    
	/* Event Application screen : Start */
    public static final String LOOKUP_PART_EVENT_APPLICATION_SEARCH = "SELECT EVENT.PART_NO, PART.BASIC_PART_NAME AS PART_NAME " +
			" FROM |!BASE_TABLE| AS EVENT, --TIX_SCHEMA--.TIBNM1 AS PART " +
			" WHERE EVENT.PART_NO = PART.TGT_BASIC_PART_NO AND EVENT.PH_COST_EVENT_NAME = '--EVENT_NAME--' AND EVENT.EVENT_REV_NO = --EVENT_REV_NO-- AND EVENT.PART_NO LIKE '--PART_NO--%' " +
			" AND PART.TGT_LANGUAGE_CODE = '2' AND PART.BASIC_PART_NAME LIKE '--PART_NAME--%' " +
			" UNION " +
			" SELECT EVENT.PART_NO, PART.PART_NAME " +
			" FROM |!BASE_TABLE| AS EVENT, FCEPN1 AS PART " +
			" WHERE EVENT.PART_NO = PART.PART_NO AND EVENT.PH_COST_EVENT_NAME = '--EVENT_NAME--' AND EVENT.EVENT_REV_NO = --EVENT_REV_NO-- AND EVENT.PART_NO LIKE '--PART_NO--%' AND PART.PART_NAME LIKE '--PART_NAME--%' " +
			" FETCH FIRST 100 ROWS ONLY ";

    public static final String LOOKUP_SUPPLIER_EVENT_APPLICATION_SEARCH = " SELECT DISTINCT EVENT.SUPPLIER_NO, SUPP.SUPPLIER_NAME "+											
    	" FROM  "+
    	" |!BASE_TABLE| AS EVENT LEFT OUTER JOIN --PUR_SCHEMA--.PUOSM1 AS SUPP ON "+
    	" EVENT.SUPPLIER_NO = SUPP.SUPPLIER_NO	 "+																
    	" WHERE "+
    	" EVENT.PH_COST_EVENT_NAME = '--EVENT_NAME--' "+
    	" AND EVENT.EVENT_REV_NO = --EVENT_REV_NO-- "+
    	" AND EVENT.SUPPLIER_NO LIKE '--SUPPLIER_NO--%' "+
    	" AND SUPP.SUPPLIER_NAME LIKE '--SUPPLIER_NAME--%' "+
    	" AND SUPP.SUPPLIER_LOC_CODE BETWEEN 0 AND 1 " +
    	" FETCH FIRST 100 ROWS ONLY ";
    
    public static final String POPULATE_EVENT_NAME_EVENT_APPLICATION = " SELECT EEM.PH_COST_EVENT_NAME, EEM.EVENT_REV_NO,  EEM.PH_COST_EVENT_NAME CONCAT '  ' CONCAT CHAR(EEM.EVENT_REV_NO)  AS EVENT,  PH_COST_EVENT_TEXT, PH_CMS_ITEM_CODE "+
																	 " FROM FCEEM1 EEM "+ 
																	 " WHERE EVENT_VISIBLE_CODE = 0 "+
																	 " AND EXISTS ( "+
																	 " SELECT * "+ 
																	 " FROM FCEAD1 EAD "+
																	 " WHERE EAD.PH_COST_EVENT_NAME = EEM.PH_COST_EVENT_NAME "+
																	 " AND EAD.EVENT_REV_NO = EEM.EVENT_REV_NO "+
																	 " AND EAD.PH_EVENT_ACT_CODE = 'LD') "+
																	 " ORDER BY EEM.PH_COST_EVENT_NAME  ";
 
	public static final String POPULATE_PART_COLOR_EVENT_APPLICATION = " SELECT DISTINCT C.CODE  ,C.CODE_DESC_TEXT  ,STRIP(C.CODE)  CONCAT ' - ' CONCAT C.CODE_DESC_TEXT AS DISPLAY_CODE "+
																	 " FROM FCERA1 AS A "+
																	 " LEFT OUTER JOIN FCCOD1 AS C "+ 
																	 " ON A.PART_COLOR_CODE = C.CODE "+ 
																	 " WHERE C.CODE_NAME = 'PART_COLOR_CODE' "+ 
																	 " ORDER BY C.CODE  ";
	
    public static final String POPULATE_PART_COLOR_EVENT_APPLICATION_DLG = " SELECT CODE ,CODE_DESC_DESC ,STRIP(PART_COLOR_CODE) CONCAT ' - '  CONCAT CODE_DESC_TEXT AS DISPLAY_CODE "+
    																 " FROM FCCOD1 WHERE CODE_NAME = 'PART_COLOR_CODE' ORDER BY PART_COLOR_CODE ";
	
	public static final String POPULATE_TARGET_PLANT_EVENT_APPLICATION = " SELECT CODE  ,CODE_DESC_TEXT ,STRIP(CODE) CONCAT ' - ' CONCAT CODE_DESC_TEXT AS DISPLAY_CODE "+
																	  " FROM FCCOD1 WHERE CODE_NAME = 'TGT_PLANT_LOC_CODE' ";
	
	public static final String POPULATE_TARGET_PLANT_EVENT_APPLICATION_DLG = " SELECT CODE  ,CODE_DESC_TEXT "+
																	  " FROM FCCOD1 WHERE CODE_NAME = 'TGT_PLANT_LOC_CODE' ";
	
	public static final String POPULATE_RPT_CURRENCY_EVENT_APPLICATION = " SELECT CODE ,CODE_DESC_TEXT ,STRIP(CODE) CONCAT ' - ' CONCAT CODE_DESC_TEXT AS DISPLAY_CODE "+
																	   " FROM --DBA_SCHEMA--.DACOD1 WHERE CODE_NAME = 'ISO_CURRENCY_CODE' ORDER BY CODE DESC  ";
	
	public static final String POPULATE_DESIGN_SECTION_EVENT_APPLICATION = " SELECT CODE  ,CODE_DESC_TEXT ,STRIP(CODE) CONCAT ' - ' CONCAT CODE_DESC_TEXT AS DISPLAY_CODE "+
																		 " FROM --DBA_SCHEMA--.DACOD1 WHERE CODE_NAME =  'PART_SECTION_CODE' ORDER BY CODE DESC  ";
	
	public static final String POPULATE_DESIGN_SECTION_EVENT_APPLICATION_DLG = " SELECT CODE  ,CODE_DESC_TEXT ,STRIP(CODE) CONCAT ' - ' CONCAT CODE_DESC_TEXT AS DISPLAY_CODE "+
	 																		   " FROM --DBA_SCHEMA--.DACOD1 WHERE CODE_NAME =  'PART_SECTION_CODE' ";
	
	public static final String POPULATE_PROC_SCTION_EVENT_APPLICATION = " SELECT CODE, CODE_DESC_TEXT, strip(CODE) CONCAT ' ' CONCAT CODE_DESC_TEXT AS PROC_SECT_CODE FROM --DBA_SCHEMA--.DACOD1 WHERE CODE_NAME = 'PROC_SECT_CODE' ORDER BY CODE ";
	
	public static final String POPULATE_FEATURE_CODE_EVENT_APPLICATION = " SELECT PRODUCT_EQUIP_CODE, Strip(PRODUCT_EQUIP_CODE) || ' - ' || PRODUCT_EQUIP_TEXT AS PRODUCT_EQUIP_TEXT, DATAITEM_SEQ_NO FROM FCBEM1 ";
	
	public static final String POPULATE_MODEL_EVENT_APPLICATION = " SELECT DISTINCT TGT_MODEL_DEV_CODE "+
																  " FROM FCERA1 "+
																  " --WHERE_CONDITION-- "+
																  " ORDER BY TGT_MODEL_DEV_CODE ";
	
	
	public static final String POPULATE_MTC_TYPE_EVENT_APPLICATION = " SELECT DISTINCT MTC_TYPE "+
																   " FROM FCERA1 "+
																   " --WHERE_CONDITION-- "+
																   " ORDER BY MTC_TYPE  ";
	
	public static final String POPULATE_MTC_OPTION_EVENT_APPLICATION = " SELECT DISTINCT MTC_OPTION "+
																	 " FROM FCERA1 "+
																	 " --WHERE_CONDITION-- "+
																	 " ORDER BY MTC_OPTION  ";
	
	public static final String POPULATE_CATEGORY_EVENT_APPLICATION = " SELECT RTRIM(CODE) AS MODEL_CAT_CODE FROM  FCCOD1 WHERE CODE_NAME = 'MODEL_CAT_CODE'  ";
	
	public static final String FREEZE_CHECK_QUERY = " SELECT EAU.UPD_ACTIVITY_CODE FROM FCEAU1 EAU WHERE EAU.PH_COST_EVENT_NAME = ? AND EAU.EVENT_REV_NO = ? ";
	
	public static final String EVENT_APPLICATION_DETAIL_DLG =  " SELECT PH_COST_EVENT_NAME "+
															   " ,EVENT_REV_NO "+
															   " ,PART_NO "+
															   " ,PART_COLOR_CODE "+
															   " ,SUPPLIER_NO "+
															   " ,SHIP_TO_CODE "+
															   " ,PART_SECTION_CODE "+
															   " ,TGT_PLANT_LOC_CODE "+
															   " ,TGT_MODEL_DEV_CODE "+
															   " ,MTC_TYPE "+
															   " ,MTC_OPTION "+
															   " ,MODEL_CAT_CODE "+
															   " ,SHARE_RATE_PERCENT "+
															   " ,PART_QTY "+
															   " FROM FCEPA1 "+
															   " WHERE PH_COST_EVENT_NAME = ? "+
															   " AND EVENT_REV_NO = ?  "+
															   " AND TRIM(PART_NO) LIKE COALESCE(?,'%') "+
															   " AND TRIM(PART_COLOR_CODE) LIKE COALESCE(?,'%') "+
															   " AND TRIM(SUPPLIER_NO) LIKE COALESCE(?,'%') "+
															   " AND TRIM(SHIP_TO_CODE) LIKE COALESCE(?,'%') "+
															   " AND TRIM(PART_SECTION_CODE) LIKE COALESCE(?,'%') "+
															   " AND TRIM(TGT_PLANT_LOC_CODE) LIKE COALESCE(?,'%') "+
															   " AND TRIM(TGT_MODEL_DEV_CODE) LIKE COALESCE(?,'%') "+
															   " AND TRIM(MTC_TYPE) LIKE COALESCE(?,'%') "+
															   " AND TRIM(MTC_OPTION) LIKE COALESCE(?,'%') "+
															   " AND TRIM(MODEL_CAT_CODE) LIKE COALESCE(?,'%') ";
	
	public static final String EVENT_APPLICATION_DETAIL = " SELECT A.PH_COST_EVENT_NAME AS \"1\", "+
														 " A.EVENT_REV_NO AS \"2\", "+
														 " A.PART_NO AS \"3\", "+
														 " C.BASIC_PART_NAME AS \"4\", "+
														 " A.PART_COLOR_CODE AS \"5\", "+
														 " A.SUPPLIER_NO AS \"6\", "+
														 " D.SUPPLIER_NAME AS \"7\", "+
														 " A.PART_SECTION_CODE AS \"11\", "+
														 " B.PLANT_LOC_CODE AS \"8\", "+
														 " A.TGT_PLANT_LOC_CODE AS \"9\", "+
														 " A.TGT_MODEL_DEV_CODE AS \"10\", "+
														 " A.MTC_TYPE AS \"12\", "+
														 " A.MTC_OPTION AS \"13\", "+
														 " A.MODEL_CAT_CODE AS \"14\" , "+
														 " A.PART_QTY AS \"16\", "+
														 " A.SHARE_RATE_PERCENT AS \"15\",  "+
														 " A.MAINT_LOGON_ID_NO AS \"17\", "+
														 " A.DATA_MAINT_PROG_NO AS \"18\", "+
														 "  A.PLANT_LOC_CODE AS \"19\" "+
														 " FROM FCEPA1 A, --TIX_SCHEMA--.TIMDL1 B, --TIX_SCHEMA--.TIBNM1 C, --PUR_SCHEMA--.PUOSM1 D "+
														 " WHERE (C.TGT_LANGUAGE_CODE = '2') "+
														 " 		AND (D.SUPPLIER_LOC_CODE IN (0, 1)) "+
														 "      AND (A.TGT_PLANT_LOC_CODE = B.TGT_PLANT_LOC_CODE) "+
														 "      AND (A.TGT_MODEL_DEV_CODE = B.TGT_MODEL_DEV_CODE) "+
														 "      AND (A.PART_NO = C.TGT_BASIC_PART_NO) "+
														 "      AND (A.SUPPLIER_NO = D.SUPPLIER_NO) "+
														 "      AND (A.PH_COST_EVENT_NAME = ? ) "+
														 "      AND (A.TGT_MODEL_DEV_CODE = ? ) "+
														 "      AND (A.MAINT_LOGON_ID_NO = ? )  "; 
	
	public static final String GET_PART_NAME_EVENT_APPLICATION = " SELECT BASIC_PART_NAME FROM --TIX_SCHEMA--.TIBNM1 WHERE TGT_BASIC_PART_NO = ?  AND TGT_LANGUAGE_CODE = '2'";

	public static final String GET_NEW_PART_NAME_APPLICATION = " SELECT PART_NAME FROM FCEPN1 WHERE PART_NO = ? ";
	public static final String GET_SUPPLIER_NAME_EVENT_APPLICATION = "  SELECT SUPPLIER_NAME FROM --PUR_SCHEMA--.PUOSM1 WHERE SUPPLIER_NO = ? ";
	
	public static final String GET_AVAILABLE_FEATURES = " SELECT PRODUCT_EQUIP_CODE  ,PRODUCT_EQUIP_TEXT "+
														" FROM FCBEM1  "+
														" WHERE PRODUCT_EQUIP_CODE NOT IN (  "+
														" SELECT PRODUCT_EQUIP_CODE  "+
														" FROM 	FCEPF1  "+
														" --WHERE_CONDITION-- "+
													    " )";
	
	public static final String GET_ASSIGNED_FEATURES =  " SELECT F.PRODUCT_EQUIP_CODE ,C.PRODUCT_EQUIP_TEXT "+
														" FROM FCEPF1 F "+
														" LEFT OUTER JOIN FCBEM1 C "+
														" ON F.PRODUCT_EQUIP_CODE = C.PRODUCT_EQUIP_CODE "+
														" --WHERE_CONDITION-- ";
	
	public static final String PART_LOOKUP_EVENT_APPLICATION_DIALOG = " SELECT TGT_BASIC_PART_NO AS PART_NO,  BASIC_PART_NAME AS PART_NAME "+
																	 " FROM  --TIX_SCHEMA--.TIBNM1 WHERE TGT_LANGUAGE_CODE = '2' AND TGT_BASIC_PART_NO LIKE '--PART_NO--%' AND BASIC_PART_NAME LIKE '--PART_NAME--%' "+
																	 " UNION "+
																	 " SELECT  PART_NO,  PART_NAME FROM FCEPN1 WHERE PART_NO LIKE '--PART_NO--%' AND PART_NAME LIKE '--PART_NAME--%' " +
																	 " FETCH FIRST 100 ROWS ONLY";
	
	
	public static final String SUPPLIER_LOOKUP_EVENT_APPLICATION_DIALOG = " SELECT DISTINCT SUPPLIER_NO, SUPPLIER_NAME FROM  --PUR_SCHEMA--.PUOSM1 "+
																		  " WHERE SUPPLIER_NO LIKE '--SUPPLIER_NO--%' AND SUPPLIER_NAME LIKE '%--SUPPLIER_NAME--%' AND SUPPLIER_LOC_CODE BETWEEN 0 AND 1 " +
																		  " FETCH FIRST 100 ROWS ONLY";

	
	public static final String ADD_FEATURE_EVENT_APPLICATION =  "   INSERT INTO FCEPF1 ("+
															    "   PH_COST_EVENT_NAME, EVENT_REV_NO,"+
															    "   PART_NO, PART_COLOR_CODE,"+
															    "   SUPPLIER_NO, PART_SECTION_CODE,"+
															    "   TGT_PLANT_LOC_CODE, TGT_MODEL_DEV_CODE,"+
															    "   MTC_TYPE, MTC_OPTION,"+
															    "   PRODUCT_EQUIP_CODE,"+
															    "   MAINT_LOGON_ID_NO, DATA_MAINT_PROG_NO,"+
															    "   DATA_MAINT_TSTP ) " +
															    "	VALUES " +
															    "	( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'FCEPAD1', CURRENT TIMESTAMP) ";
	
	
	public static final String REMOVE_FEATURE_EVENT_APPLICATION =  "   DELETE FROM FCEPF1 "+
																   "   WHERE PH_COST_EVENT_NAME = ? "+
																   "   AND EVENT_REV_NO = ? "+
																   "   AND PART_NO = ? "+
																   "   AND PART_COLOR_CODE = ? "+
																   "   AND SUPPLIER_NO = ? "+
																   "   AND PART_SECTION_CODE = ? "+
																   "   AND TGT_PLANT_LOC_CODE = ? "+
																   "   AND TGT_MODEL_DEV_CODE = ? "+
																   "   AND MTC_TYPE = ? "+
																   "   AND MTC_OPTION = ? "+
																   "   AND PRODUCT_EQUIP_CODE = ? ";
	
   public static final String PART_SUPPLIER_VALIDATION_CHECK = " SELECT 1 "+
														       " FROM FCEPM1 "+
														       " WHERE PH_COST_EVENT_NAME = ? "+
														       " AND EVENT_REV_NO = ? "+
														       " AND PART_NO = ? "+
														       " AND PART_COLOR_CODE = ? "+
														       " AND SUPPLIER_NO = ? ";
   
   public static final String GET_EVENT_APPLICATION_DETAILS =  " SELECT PH_COST_EVENT_NAME " +
															   " ,EVENT_REV_NO " +
															   " ,PART_NO " +
															   " ,PART_COLOR_CODE " +
															   " ,SUPPLIER_NO " +
															   " ,SHIP_TO_CODE " +
															   " ,PART_SECTION_CODE " +
															   " ,TGT_PLANT_LOC_CODE " +
															   " ,TGT_MODEL_DEV_CODE " +
															   " ,MTC_TYPE " +
															   " ,MTC_OPTION " +
															   " ,MODEL_CAT_CODE " +
															   " ,SHARE_RATE_PERCENT " +
															   " ,PART_QTY " +
															   " ,IS_DSPS " +
															   " ,CASE WHEN DATA_MAINT_PROG_NO ='FCS745B' then 'Y' else 'N' end IS_COPY_BOM" +
															   " FROM FCEPA1 " +
															   " --WHERE_CONDITION-- ";
   
   public static String POPULATE_PART_COLOR_EVENT_APPLICATION_COPY = " SELECT DISTINCT A.PART_COLOR_CODE, Strip( A.PART_COLOR_CODE) || ' - ' || C.CODE_DESC_TEXT AS CODE_DESC_TEXT "+ 
																	" FROM FCERA1 AS A LEFT OUTER JOIN FCCOD1 AS C "+
																	" ON A.PART_COLOR_CODE = C.CODE  "+
																	" WHERE C.CODE_NAME = 'PART_COLOR_CODE' ORDER BY PART_COLOR_CODE"; 
   
   public static String POPULATE_TARGET_PLANT_EVENT_APPLICATION_COPY = " SELECT CODE ,CODE_DESC_TEXT FROM --DBA_SCHEMA--.DACOD1 WHERE CODE_NAME = 'TGT_PLANT_LOC_CODE' "; 
   
   public static String POPULATE_DESIGN_SECTION_EVENT_APPLICATION_COPY = " SELECT CODE,CODE_DESC_TEXT ,STRIP(CODE) CONCAT ' - ' CONCAT CODE_DESC_TEXT AS DISPLAY_CODE "+
   																		 " FROM --DBA_SCHEMA--.DACOD1 WHERE CODE_NAME =  'PART_SECTION_CODE' "; 
   
   public static String POPULATE_MODEL_EVENT_APPLICATION_COPY = " SELECT DISTINCT TGT_MODEL_DEV_CODE "+
																" FROM FCERA1 "+
																" --WHERE_CONDITION-- "+
																" ORDER BY TGT_MODEL_DEV_CODE "; 
   
   public static String POPULATE_SHIP_TO_CODE_EVENT_APPLICATION_COPY = " SELECT DISTINCT SHIP_TO_CODE FROM FCEPA1 ORDER BY SHIP_TO_CODE "; 
   
   public static String POPULATE_MTC_TYPE_EVENT_APPLICATION_COPY =  " SELECT DISTINCT MTC_TYPE "+
																	" FROM FCERA1 "+
																	" --WHERE_CONDITION-- "+																	
																	" ORDER BY MTC_TYPE"; 
   
   public static String POPULATE_MTC_OPTION_EVENT_APPLICATION_COPY =   " SELECT DISTINCT MTC_OPTION "+
																	   " FROM FCERA1 "+
																	   " --WHERE_CONDITION-- "+
																	   " ORDER BY MTC_OPTION "; 
   
   public static String POPULATE_CATEGORY_EVENT_APPLICATION_COPY = " SELECT RTRIM(CODE) AS MODEL_CAT_CODE FROM  FCCOD1 WHERE CODE_NAME = 'MODEL_CAT_CODE' "; 
   
   public static final String GET_EVENT_APPLICATION_COPY_DETAILS =   " SELECT PH_COST_EVENT_NAME "+
															   " ,EVENT_REV_NO "+
															   " ,PART_NO "+
															   " ,PART_COLOR_CODE "+
															   " ,SUPPLIER_NO "+
															   " ,SHIP_TO_CODE "+
															   " ,PART_SECTION_CODE "+
															   " ,TGT_PLANT_LOC_CODE "+
															   " ,TGT_MODEL_DEV_CODE "+
															   " ,MTC_TYPE "+
															   " ,MTC_OPTION "+
															   " ,MODEL_CAT_CODE "+
															   " ,SHARE_RATE_PERCENT "+
															   " ,PART_QTY "+
															   " FROM FCEPA1 "+
															   " WHERE PH_COST_EVENT_NAME = ? "+
															   " AND EVENT_REV_NO = ? "+ 
															   " AND PART_NO = ? "+
															   " AND PART_COLOR_CODE = ? "+
															   " AND SUPPLIER_NO = ? "+
															   " AND SHIP_TO_CODE = ? "+
															   " AND PART_SECTION_CODE = ? "+
															   " AND TGT_PLANT_LOC_CODE = ? "+
															   " AND TGT_MODEL_DEV_CODE = ? "+
															   " AND MTC_TYPE = ? "+
															   " AND MTC_OPTION = ? "+
															   " AND MODEL_CAT_CODE = ? " ;
   
   public static final String UPDATE_EVENT_APPLICATION_COPY =   " UPDATE FCEPA1 "+
																" SET SHARE_RATE_PERCENT = ?, "+ 
																" PART_QTY = ? "+
																" WHERE PH_COST_EVENT_NAME = ? AND "+
																" EVENT_REV_NO = ? AND "+ 
																" PART_NO = ? AND  "+
																" PART_COLOR_CODE = ? AND "+
																" SUPPLIER_NO = ? AND  "+
																" SHIP_TO_CODE = ? AND  "+
																" PART_SECTION_CODE = ? AND PLANT_LOC_CODE = ? AND "+ 
																" TGT_PLANT_LOC_CODE = ? AND  "+
																" TGT_MODEL_DEV_CODE = ? AND  "+
																" MTC_TYPE = ? AND  "+
																" MTC_OPTION = ? AND "+
																" MODEL_CAT_CODE = ? ";
   
   public static final String DELETE_EVENT_APPLICATION_COPY =   " DELETE FROM FCEPA1  "+
																" WHERE PH_COST_EVENT_NAME = ? AND "+
																               " EVENT_REV_NO = ? AND "+ 
																               " PART_NO = ? AND "+ 
																               " PART_COLOR_CODE = ? AND "+
																               " SUPPLIER_NO = ? AND "+ 
																               " SHIP_TO_CODE = ? AND "+ 
																               " PART_SECTION_CODE = ? AND "+ 
																               " TGT_PLANT_LOC_CODE = ? AND "+ 
																               " TGT_MODEL_DEV_CODE = ? AND "+ 
																               " MTC_TYPE = ? AND "+ 
																               " MTC_OPTION = ?  AND "+
																               " MODEL_CAT_CODE = ? ";
   
   public static final String GET_AVAILABLE_FEATURES_COPY = " SELECT EPF.PRODUCT_EQUIP_CODE "+
														   " ,BEM.PRODUCT_EQUIP_TEXT "+
														   " FROM FCEPF1 EPF "+
														   " INNER JOIN FCBEM1 BEM "+
														   " ON BEM.PRODUCT_EQUIP_CODE = EPF.PRODUCT_EQUIP_CODE "+
														   " --WHERE_CONDITION-- ";
   
   public static final String GET_ASSIGNED_FEATURES_COPY = " SELECT C.PRODUCT_EQUIP_CODE ,C.PRODUCT_EQUIP_TEXT FROM FCBEM1 C WHERE 1=0 ";
   
   public static final String PLANT_MTO_COLOR_VALIDATION = " SELECT 1 "+
														   " FROM FCERA1 "+
														   " WHERE PH_COST_EVENT_NAME = ? "+
														   " AND EVENT_REV_NO = ? "+
														   " AND TGT_PLANT_LOC_CODE = ? "+
														   " AND TGT_MODEL_DEV_CODE = ? "+
														   " AND MTC_TYPE = ? "+
														   " AND MTC_OPTION = ? "+
														   " AND PART_COLOR_CODE = ? ";
   //pscc-6605-change
   public static final String APPLY_EVENT_APPLICATION =
		      " UPDATE FCEPA1 "
		    + " SET SHARE_RATE_PERCENT = ?, "
		    + " PART_QTY = ?, "
		    + " PART_SECTION_CODE = ?, "   
		    + " IS_DSPS = ?, "
		    + " MAINT_LOGON_ID_NO = ?, "
		    + " DATA_MAINT_PROG_NO = ?, "
		    + " DATA_MAINT_TSTP = CURRENT TIMESTAMP "
		    + " WHERE PH_COST_EVENT_NAME = ? AND "
		    + " EVENT_REV_NO = ? AND "
		    + " PART_NO = ? AND "
		    + " PART_COLOR_CODE = ? AND "
		    + " SUPPLIER_NO = ? AND "
		    + " SHIP_TO_CODE = ? AND "
		    + " PART_SECTION_CODE = ? AND "
		    + " PLANT_LOC_CODE = ? AND "
		    + " TGT_PLANT_LOC_CODE = ? AND "
		    + " TGT_MODEL_DEV_CODE = ? AND "
		    + " MTC_TYPE = ? AND "
		    + " MTC_OPTION = ? AND "
		    + " MODEL_CAT_CODE = ? ";

 //pscc-6605-change

	/* Event Application screen : End */
   /* To get the actual event attached to budget and its rev number*/
   public static final String CHECK_ACTEVENT_INANYPRIOR_EVENT = " SELECT TRIM(EDS.PH_COST_EVENT_NAME) AS PH_COST_EVENT_NAME,TRIM(EDS.EVENT_REV_NO) AS EVENT_REV_NO  FROM FCEDS1 EDS " +
   	" join FCEEM1 EEM ON EDS.PH_COST_EVENT_NAME = EEM.PH_COST_EVENT_NAME" +
	" WHERE  EDS.PRIOR_EVENT_NAME = ? AND EDS.PRIOR_EVENT_REV_NO = ? AND EEM.PH_CMS_ITEM_CODE = 'BUCE' order by EDS.EVENT_REV_NO desc";


    public static final String INSERT_NEW_PART = "INSERT INTO FCEPN1 (PART_NO ,PART_NAME ,MAINT_LOGON_ID_NO ,DATA_MAINT_PROG_NO ,DATA_MAINT_TSTP) " +
    		" VALUES (? , ? , ? , ? ,CURRENT TIMESTAMP)";
    
    public static final String IMP_FILE_DATA = "CALL --PROC_SCHEMA--.FCS804P ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
   
    
    public static final String CHECK_EVENT_SECURITY = " SELECT EAU.UPD_ACTIVITY_CODE  FROM FCEAU1 EAU " +
    		" WHERE  EAU.PH_COST_EVENT_NAME = ? AND EAU.EVENT_REV_NO = ? ";
    

    public static final String UPDATE_EVENT_PART_COST_INLINE = " UPDATE FCEPC1  " +
    " SET COST_CHANGE_AMT = ? , " +
    " MAINT_LOGON_ID_NO = ?, " +
    " DATA_MAINT_PROG_NO = 'FCEPCS1', " +
    " DATA_MAINT_TSTP = CURRENT TIMESTAMP " +
    " WHERE PH_COST_EVENT_NAME = ? " +
    " AND EVENT_REV_NO = ? " +
    " AND PART_NO = ? " +
    " AND PART_COLOR_CODE = ? " +
    " AND SUPPLIER_NO = ? " + 
    " AND PLANT_LOC_CODE = ? " +
    " AND COST_CHG_CAT_CODE = 'BC' ";
    
    
    public static final String UPDATE_EVENT_PART_COST_MPCE = "UPDATE FCEPM1 " +
    		" SET INV_STAGE_CODE = ?, " +
    		" PART_ADD_CODE = ?, " +
    		" DC_NO = ?, " +
    		" SHIP_FROM _TO_CODE = ?, " +
    		" PROC_SECT_CODE = ?, " +
    		" EST_CYCLE_UNIT_QTY = ?, " +
    		" INVEST_COST_CODE = ?, " +
    		" RPT_CURRENCY_CODE = ?, " +
    		" ISO_CURRENCY_CODE = ? " +
    		" WHERE PH_COST_EVENT_NAME = ? AND " +
    		" EVENT_REV_NO = ? AND " +
    		" PART_NO = ? AND " +
    		" PART_COLOR_CODE = ? AND " +
    		"SUPPLIER_NO = ?";
    
    /**
     * Project Id: PR03601 CART 2 Phase 2.
     * Added as part of Use case: 22 - Perform Cost Maintenance
     * Retrieves cost change code list with description
     */
    public static final String COST_CHANGE_CODES = "SELECT (CODE) CONCAT ' - ' CONCAT CODE_DESC_TEXT AS DISPLAY_CODE, GCG.COST_CHANGE_CODE, COD.CODE_DESC_TEXT "+
    			" FROM FCGCG1 GCG INNER JOIN FCCOD1 COD ON GCG.COST_CHANGE_CODE = COD.CODE "+
    			" WHERE GCG.COST_FUNC_GRP_CODE = 'PPQU' AND COD.CODE_NAME = 'COST_CHANGE_CODE'";
    
    
    /**
     * Project Id: PR03601 CART 2 Phase 2.
     * Added as part of Use case: 22 - Perform Cost Maintenance
     * Retrieves QUOTE NUMBER for the underlying part number
     */
    public static final String GET_QUOTE_NO = "SELECT QUOTE_NO FROM FCPHF1 WHERE PART_NO=? AND SUPPLIER_NO=? AND PLANT_LOC_CODE=? AND ACT_QUOTE_EFF_DATE=?";
    
    
    /**
     * Project Id: PR03601 CART 2 Phase 2.
     * Added as part of Use case: 22 - Perform Cost Maintenance
     * Retrieves QUOTE COMMENTS for the underlying part number
     */
    public static final String GET_QUOTE_COMMENTS = "SELECT BUYER_SUPLR_COMMNT FROM --EQUOTE_UDB_SCHEMA--.EXQCM1 WHERE SUPLR_STG_ID = (SELECT SUPLR_STG_ID " +
    		" FROM --EQUOTE_UDB_SCHEMA--.EXQOT1 WHERE QUOTE_NO = ?)";
    
    /**
     * START : Queries for applying cost changes to budget event attached to ACT event
     */
    public static final String GET_BUDGET_FORECAST_COST = "SELECT COST_CHANGE_AMT FROM FCEPC1 WHERE PH_COST_EVENT_NAME = ? AND EVENT_REV_NO = ?" +
    		" AND PART_NO = ? AND SUPPLIER_NO = ? AND PLANT_LOC_CODE = ? AND COST_CHANGE_CODE = ? AND ACT_QUOTE_EFF_DATE = ? AND COST_CHG_CAT_CODE = 'BFC'";
    
    public static final String GET_MCC_FOR_BUDGET = "SELECT COST_CHANGE_AMT FROM FCEPC1 WHERE PH_COST_EVENT_NAME = ? AND EVENT_REV_NO = ?" +
	" AND PART_NO = ? AND SUPPLIER_NO = ? AND PLANT_LOC_CODE = ? AND COST_CHANGE_CODE = ? AND ACT_QUOTE_EFF_DATE = ? AND COST_CHG_CAT_CODE = 'MCC'";
    
    public static final String UPDATE_BUDGET_FORECAST_COST = "UPDATE FCEPC1 SET COST_CHANGE_AMT = ?, COST_CHANGE_AMT_JPY = ?, MAINT_LOGON_ID_NO = ?, DATA_MAINT_TSTP = CURRENT TIMESTAMP, DATA_MAINT_PROG_NO = 'FCEPCD2' WHERE PH_COST_EVENT_NAME = ? AND EVENT_REV_NO = ?" +
		" AND PART_NO = ? AND SUPPLIER_NO = ? AND PLANT_LOC_CODE = ? AND COST_CHANGE_CODE = ? AND ACT_QUOTE_EFF_DATE = ? AND COST_CHG_CAT_CODE = 'BFC'";
    
    public static final String UPDATE_MCC_FOR_BUDGET = "UPDATE FCEPC1 SET COST_CHANGE_AMT = ?,  COST_CHANGE_AMT_JPY = ?, MAINT_LOGON_ID_NO = ?, DATA_MAINT_TSTP = CURRENT TIMESTAMP, DATA_MAINT_PROG_NO = 'FCEPCD2' WHERE PH_COST_EVENT_NAME = ? AND EVENT_REV_NO = ?" +
		" AND PART_NO = ? AND SUPPLIER_NO = ? AND PLANT_LOC_CODE = ? AND COST_CHANGE_CODE = ? AND ACT_QUOTE_EFF_DATE = ? AND COST_CHG_CAT_CODE = 'MCC' ";
    
    public static final String DELETE_BUDGET_FORECAST_COST = "DELETE FROM FCEPC1 WHERE PH_COST_EVENT_NAME = ? AND EVENT_REV_NO = ?" +
	" AND PART_NO = ? AND SUPPLIER_NO = ? AND PLANT_LOC_CODE = ? AND COST_CHANGE_CODE = ? AND ACT_QUOTE_EFF_DATE = ? AND COST_CHG_CAT_CODE = 'BFC'";
    
    public static final String INSERT_MCC_FOR_BUDGET = "INSERT INTO FCEPC1 (PH_COST_EVENT_NAME, EVENT_REV_NO, PART_NO, PART_COLOR_CODE, PLANT_LOC_CODE," +
    		" SUPPLIER_NO, COST_BEG_EFF_DATE, COST_CHG_CAT_CODE, COST_CHANGE_CODE, COST_CHANGE_AMT, ACT_QUOTE_EFF_DATE, MAINT_LOGON_ID_NO, DATA_MAINT_PROG_NO," +
    		" DATA_MAINT_TSTP, ISO_CURRENCY_CODE, COMMENT_TEXT, COST_CHANGE_AMT_JPY) " +
    		" VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT TIMESTAMP, ?, ?, ?)";
    
    public static final String DELETE_BUDGET_MCC = "DELETE FROM FCEPC1 WHERE PH_COST_EVENT_NAME = ? AND EVENT_REV_NO = ?" +
	" AND PART_NO = ? AND SUPPLIER_NO = ? AND PLANT_LOC_CODE = ? AND COST_CHANGE_CODE = ? AND ACT_QUOTE_EFF_DATE = ? AND COST_CHG_CAT_CODE = 'MCC'";
    /**
     * END : Queries for applying cost changes to budget event attached to ACT event
     */
    
    /**
     * START : Queries used for retrieving exchange rates
     */
    public static final String GET_END_DATE_FCEEM1_EXCHANGE_RATE = "SELECT END_TIMESTAMP FROM FCEEM1 WHERE PH_COST_EVENT_NAME=? AND EVENT_REV_NO=?";
	
    public static final String GET_END_DATE_FCEAD1_EXCHANGE_RATE = "SELECT PH_EVENT_ACT_TSTP FROM FCEAD1 WHERE PH_COST_EVENT_NAME=? AND EVENT_REV_NO=? AND PH_EVENT_ACT_CODE='LD'";
    
    public static final String GET_END_DATE_FCEAD1 = "SELECT PH_EVENT_ACT_TSTP FROM FCEAD1 WHERE PH_COST_EVENT_NAME=? AND EVENT_REV_NO=? AND PH_EVENT_ACT_CODE='LD'";

    public static final String GET_EXCHANGE_RATES_FOR_JPY = "SELECT EXCHANGE_RATE_AMT, FOB_RATE FROM FCRAT1 WHERE KI_YEAR=? AND MONTH=? " +
				" AND TO_ISO_CUR_CODE=? AND FROM_ISO_CUR_CODE = ? AND SOURCE='HR' AND VERSION='ACT'";
    /**
     * END : Queries used for retrieving exchange rates
     */
    
    public static final String GET_FEMD_MODEL = "SELECT --COLUMN-- FROM FCEFM1 WHERE PH_COST_EVENT_NAME = ? AND EVENT_REV_NO = ?" +
    		" AND TGT_MODEL_DEV_CODE = ? AND MTC_TYPE = ? AND MTC_OPTION = ? ";
    
    public static final String CHECK_FOR_OLD_EVENTS = "SELECT COUNT(*) FROM FCEPC1 WHERE PH_COST_EVENT_NAME = ? AND EVENT_REV_NO = ? AND ISO_CURRENCY_CODE = 'JPY'";
    
    public static final String GET_MODEL_CAT_CODE_ON_MODEL_SELECTION = "SELECT DISTINCT MODEL_CAT_CODE FROM --TIX_SCHEMA--.TIMDL1 WHERE TGT_MODEL_DEV_CODE=?";
    
    public static final String UPDATE_MCC_CODE_IF_CHANGED = "UPDATE FCEPC1 SET MAINT_LOGON_ID_NO = ?, DATA_MAINT_TSTP = CURRENT TIMESTAMP, COST_CHANGE_CODE=?," +
    		" DATA_MAINT_PROG_NO=? WHERE PH_COST_EVENT_NAME = ? AND EVENT_REV_NO = ? AND PART_NO = ? AND PART_COLOR_CODE = ? " +
    		" AND SUPPLIER_NO = ? AND PLANT_LOC_CODE = ? AND COST_CHG_CAT_CODE = 'MCC' AND COST_CHANGE_CODE=? AND ACT_QUOTE_EFF_DATE=?";

	public static final String CHECK_FOR_SUPP_BY_EVENT_AND_PART = "SELECT COUNT(DISTINCT(SUPPLIER_NO)) FROM FCEPA1 WHERE PART_NO = ? AND PH_COST_EVENT_NAME = ? AND EVENT_REV_NO = ?";

}
